### ISSUE TITLE
Cannot connect new eNet server V2.2.1

### ISSUE THREAD

**Issue by kustershjh** [SebastianSchultz/ioBroker.enet#21]
Dear,

Please note that I'm using the newest (DIN rail) eNet server and would like to use ioBroker. I created the enet.0 instance using this adapter but encounter an error (below):

instance system.adapter.enet.0 terminated with code 10 (CANNOT_FIND_ADAPTER_DIR)

Will you be able to update the adapter to include the latest server hardware of Gira/Jung eNet server?

Thanks!

**Comment by SebastianSchultz** [comment]
Sorry, enet Server is currently not supported. Im working on it.
Only enet Gateway is supported.

**Comment by kustershjh** [comment]
Okay, thanks for your prompt reply. I would be excited to see the new adapter in the future.

**Comment by SebastianSchultz** [comment]
I'm working currently on the server implementation :)
