### ISSUE TITLE
Adapter kommt bei Bezeichnungen mit Punkt durcheinander

### ISSUE THREAD

**Issue by engiadina** [SebastianSchultz/ioBroker.enet#24]
Beim Auslesen der eNet Struktur über den eNet Server führen Bezeichnungen mit Punkt zu Fehlern. Bsp: 1. Stock
[1598960845250-enet.log](https://github.com/SebastianSchultz/ioBroker.enet/files/5158163/1598960845250-enet.log)

**Comment by SebastianSchultz** [comment]
Hallo,

ich habe den Code mal abgeändert. Jetzt sollten Leerzeichen und Punkte in Raum- oder Stockwerknamen durch Unterstriche ersetzt werden. 

Hier der Adapter in der abgeänderten Form: [iobroker.enet.zip](https://github.com/SebastianSchultz/ioBroker.enet/files/5165009/iobroker.enet.zip)

Bitte gib mir dazu mal ein Feedback.

**Comment by engiadina** [comment]
Hallo Sebastian,

das mit den Stockwerken klappt schon mal gut. Allerdings werden die Räume nicht korrekt zugeordnet und jetzt kann ich auch keine Werte mehr auslesen.

Ich habe Dir mal die Log-Datei sowie den Screenshot der Objekte angehängt.
[enet.log](https://github.com/SebastianSchultz/ioBroker.enet/files/5168151/enet.log)
![Bildschirmfoto 2020-09-03 um 13 21 03](https://user-images.githubusercontent.com/2302158/92109327-1a24be80-ede9-11ea-976a-826ce9e9f7b4.png)

**Comment by SebastianSchultz** [comment]
Hast Du mal den Objektebaum komplett neu eingelesen (im Reiter Objekte mal oben links den Button mit dem Pfeil klicken. Der nennt sich "Baum  neu erstellen".

**Comment by engiadina** [comment]
Hab ich, hat aber nicht übermässig viel geändert.

![Bildschirmfoto 2020-09-03 um 13 37 10](https://user-images.githubusercontent.com/2302158/92110206-a5528400-edea-11ea-9b2b-eeb2ec72cf04.png)

Der Adapter ignoriert wohl die Stockwerkszuordnung.

Das der erste Stock / Schlafzimmer passt jetzt. Da gibt es fünf Komponenten, die auch alle da sind und mit Werten abgebildet. Auch die Bezeichnungen stimmen.

Das Ergeschoss hat drei Räume (Küche, Esszimmer, Wohnzimmer). Die sind nicht da offensichtlich, während die fünf Komponenten des "angeblichen Schlafzimmers" mit korrekten Bezeichnungen der Komponenten des Wohnzimmers belegt sind. Aber es gibt keine Werte dazu.

**Comment by engiadina** [comment]
Ach ich vergass, den "Fehler"

No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }

gibts immer noch, aber wie ich gesehen habe, ist der nicht besonders spannend.

**Comment by SebastianSchultz** [comment]
`No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }`

Kannst Du ignorieren :)
Kannst Du nochmal alle Objekte löschen, das Debug Log aktivieren und den Adapter neu starten, damit die Objekte neu eingelesen werden?
Ich bräuchte dann mal dasLog. Kann sein das es noch "unbekannte" Geräte sind.

**Comment by engiadina** [comment]
Hab ich ignoriert ...

ich denke, dass der Adapter irgendwie mit den Stockwerken nicht klar kommt ...

hier kommt das Log, vom Ergebnis hat sich nichts geändert 

[enet3.log](https://github.com/SebastianSchultz/ioBroker.enet/files/5169255/enet3.log)

**Comment by SebastianSchultz** [comment]
Ich vermute er kommt durcheinander, weil er Geräte aus dem eNet Server ausliest, die er nicht kennt und die bisher auch noch nicht implementiert sind:

`GetDevices Error: Unknown Device: DVT_WS3BG
GetDevices Error: Unknown Device: DVT_SA1Z
GetDevices Error: Unknown Device: DVT_SD1M
GetDevices Error: Unknown Device: DVT_SA1Z
GetDevices Error: Unknown Device: DVT_WS3BG
GetDevices Error: Unknown Device: DVT_WS3BG
`

Kannst Du sagen, was für Geräte das genau sind?

**Comment by engiadina** [comment]
Ich muss mal raten ... natürlich weiss ich, was verbaut ist, aber ob ich das den Abkürzungen zuordnen kann muss ich sehen:

DVT_WS3BG müsste ein Wandsender 3fach sein (Gira 5333 100, https://katalog.gira.de/de_DE/datenblatt.html?id=651164)

DVT_SA1Z müsste der Funk Schaltaktor SZ sein (Gira 5448 02, https://katalog.gira.de/de_DE/datenblatt.html?id=635910)

DVT_SD1M müsste die Funk Steuereinheit DALI 1fach Mini sein (Gira 5422 00, https://katalog.gira.de/de_DE/datenblatt.html?id=635927)

Tatsächlich kann man ja ein Probeprojekt im Server anlegen mit lauter Kataloggeräten. Wenn man das ausliest, müsste man eigentlich eine recht komplette Liste aller möglichen Geräte bekommen ...

**Comment by shanse01** [comment]
Moin Sebastian,
zuerst einmal vielen Dank für die Arbeit, die Du in dieses Projekt steckst. Eine Frage, die mir aus dem Lesen der verschiedenen Quellen nicht klar wurde: Funktioniert der Zugriff auf den Server jetzt, wenn auch noch nicht vollständig, oder läuft weiterhin "nur" das Gateway? Ich habe heute über den ganzen Tag versucht den hier geposteten Adapter zu installieren, bekomme aber keinen Connect hin.

Das log sagt folgendes:

enet.0 | 2020-09-27 21:55:32.016 | info | (2394) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
enet.0 | 2020-09-27 21:55:32.015 | info | (2394) terminating
enet.0 | 2020-09-27 21:55:31.998 | error | (2394) TypeError: Cannot read property 'toString' of undefined at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:282:62) at Object.onceWrapper (events.js:422:26)
enet.0 | 2020-09-27 21:55:31.996 | error | (2394) uncaught exception: Cannot read property 'toString' of undefined
enet.0 | 2020-09-27 21:55:31.857 | info | (2394) Running eNet Adapter Version 1.0.1, Configured eNet Server: 192.168.5.222, Username: admin
enet.0 | 2020-09-27 21:55:31.830 | info | (2394) starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.enet, node: v12.18.3, js-controller: 3.1.6
enet.0 | 2020-09-27 21:55:00.088 | info | (2334) Terminated (NO_ERROR): Without reason
enet.0 | 2020-09-27 21:55:00.087 | info | (2334) terminating
enet.0 | 2020-09-27 21:55:00.073 | error | (2334) TypeError: Cannot read property 'toString' of undefined at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:282:62) at Object.onceWrapper (events.js:422:26)
enet.0 | 2020-09-27 21:55:00.071 | error | (2334) uncaught exception: Cannot read property 'toString' of undefined
enet.0 | 2020-09-27 21:54:59.980 | info | (2334) Running eNet Adapter Version 1.0.1, Configured eNet Server: 192.168.5.222, Username: admin
enet.0 | 2020-09-27 21:54:59.953 | info | (2334) starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.enet, node: v12.18.3, js-controller: 3.1.6
enet.0 | 2020-09-27 20:54:28.244 | info | (2319) Terminated (NO_ERROR): Without reason
enet.0 | 2020-09-27 20:54:28.243 | info | (2319) terminating
enet.0 | 2020-09-27 20:54:28.225 | error | at Socket.Readable.push (_stream_readable.js:212:10)
enet.0 | 2020-09-27 20:54:28.225 | error | at readableAddChunk (_stream_readable.js:271:9)
enet.0 | 2020-09-27 20:54:28.225 | error | at addChunk (_stream_readable.js:295:12)
enet.0 | 2020-09-27 20:54:28.225 | error | at Socket.emit (events.js:315:20)
enet.0 | 2020-09-27 20:54:28.225 | error | at Socket.socketOnData (_http_client.js:469:22)
enet.0 | 2020-09-27 20:54:28.225 | error | at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
enet.0 | 2020-09-27 20:54:28.225 | error | at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
enet.0 | 2020-09-27 20:54:28.225 | error | at ClientRequest.emit (events.js:315:20)
enet.0 | 2020-09-27 20:54:28.225 | error | at Object.onceWrapper (events.js:422:26)
enet.0 | 2020-09-27 20:54:28.225 | error | at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:282:62)
enet.0 | 2020-09-27 20:54:28.225 | error | (2319) TypeError: Cannot read property 'toString' of undefined
enet.0 | 2020-09-27 20:54:28.223 | error | (2319) uncaught exception: Cannot read property 'toString' of undefined
enet.0 | 2020-09-27 20:54:28.125 | info | (2319) Running eNet Adapter Version 1.0.1, Configured eNet Server: 192.168.5.222, Username: admin
enet.0 | 2020-09-27 20:54:28.098 | info | (2319) starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.enet, node: v12.18.3, js-controller: 3.1.6
enet.0 | 2020-09-27 20:53:56.437 | info | (2258) Terminated (NO_ERROR): Without reason
enet.0 | 2020-09-27 20:53:56.436 | info | (2258) terminating

Ich bin recht neu unterwegs mit dem ioBroker, daher kann es sicher sein, dass ich es schlicht falsch gemacht habe.
Habe alle eNet-Instanzen und Adapter vorher entfernt. mit wget den zip-file geladen und im angegebenen Verzeichnis entpackt. Dann die ioBrocker Adminseite neu geladen und eine neue Instanz des eNet-Adapters installiert. IP-Adresse, Benutzernamen und Kennwort hinterlegt und die Instanz gestartet.

Bin für jeden Hinweis dankbar.

Besten Gruß
Sven Hansen

**Comment by SebastianSchultz** [comment]
Momentan funktioniert der Zugriff auf den Server nur sehr rudimentär in einer Alpha Version, die hier noch nicht veröffentlicht wurde :)

**Comment by shanse01** [comment]
OK, Danke für die Info. Hatte versucht als "Testkaninchen" zur Verfügung zu stehen, scheitere aber scheinbar schon an der korrekten Installation der Alpha Version :(.
