### ISSUE TITLE
Bekomme den eNet-Adapter weder aus dem Raspberry noch als Windows-Installation ans laufen

### ISSUE THREAD

**Issue by FranzKillig** [SebastianSchultz/ioBroker.enet#25]
Hallo,

da ich eine recht umfangreiche eNet-Installation zuhause habe und diese aber mit anderen Smarthomelösungen verquicken möchte bin ich auf ioBroker gestoßen. Als erstes habe ich mir ein ioBroker-System auf einem Rapberry Pi 4 Mod. B 8Gb zusammen gebastelt. Nach dem ich dort schon mit den gleichen Fehlermeldungen den eNet-Adapter nicht zum
laufen bekommen habe, habe ich es nun noch unter Windows versucht. Allerdings habe ich hier genau das gleiche Problem:

Auszug aus Log:

![image](https://user-images.githubusercontent.com/70587675/93487316-6dc4fb00-f905-11ea-9c3d-677c29199312.png)

Meine eNet-Anlage besteht aus:

eNet Server 2.2.1 mit fester IP
2 Steuereinheit DALI 1fach Mini FMSTD8UP
5 Schalt-/Tastaktor 2fach Mini FMAS26UP
5 Schalt-/Tastaktor 8fach / Jalousieaktor 4fac… FMAS816REG
1 Dimmaktor 1fach REG FMUD5500REG
3 Universalsender 2fach Mini FMUS2UP
1 Schalt-/Tastaktor 1fach Mini potentialfrei FMASPF10UP
4 Wandsender-Modul 2fach FM4002M
7 Wandsender-Modul 1fach FM4001M
2 Schalt-/Tastaktor 1fach Mini FMAS10UP
4 Wandsender-Modul 4fach FM4004M
6 Jalousieaktor 1fach Mini FMJ50700UP

Ich habe im Moment keinen Plan, wo ich mit der Fehlersuche beginnen soll. Würde mich sehr freuen, wenn ich wenigstens
einen Anhaltspunkt für die Fehlersuche bekommen würde.

Gruß
Franz

**Comment by SebastianSchultz** [comment]
Hallo,

derzeit funktioniert die Github Version noch nicht mit eNet Servern.
Wenn Du aber selbst entwickeln kannst, kannst Du gern helfen, es gibt bereits eine Alpha Version die bereits mit eNet Servern kommunizieren kann.

**Comment by FranzKillig** [comment]
Hallo Sebastian,
ich komme zwar ursprünglich aus der Prozess- und Gebäudeleittechnik und habe bis vor ca. 16 Jahren selbst Anlagen in diversen Programmiersprachen wie Pascal und ähnlichem programmiert, mit Javascript habe ich mich bisher jedoch nicht wirklich auseinander gesetzt. Will mich aber in den nächsten Monaten in die Materie einlesen. Ob ich im Moment deshalb viel an der Entwicklung des Adapters mitwirken kann weis ich nicht. Bin aber auf jedenfalls gerne bereit meine Installationsumgebung als Testfeld zur Verfügung zu stellen. Eventuell ist auch denkbar, das ich die eine oder andere Hardware für Testzwecke zur Verfügung stellen kann.

**Comment by SebastianSchultz** [comment]
Wäre toll, wenn Du bei der Entwicklung unterstützen könntest.
Ich könnte momentan jede Hilfe gebrauchen :)
