### ISSUE TITLE
Fehlermeldung Object enet.0.rooms.room19.NAME is invalid: obj.common.read has an invalid type! Expected "boolean", received "string"

### ISSUE THREAD

**Issue by daNick73** [SebastianSchultz/ioBroker.enet#26]
Hallo,

der eNet Adapter funktioniert, allerdings habe ich folgende Fehlermeldung im Log

```
Object enet.0.rooms.room19.NAME is invalid: obj.common.read has an invalid type! Expected "boolean", received "string"
This object will not be created in future versions. Please report this to the developer.
```

Danke für den Adapter!

daNick

**Comment by SebastianSchultz** [comment]
Hallo,

danke für die Info. Wird in einer der nächsten Versionen gefixt.

**Comment by daNick73** [comment]
Danke, danke, danke für den Adapter!

Sebastian Schultz <notifications@github.com> schrieb am Sa. 26. Sept. 2020
um 12:38:

**Comment by mtoensing** [comment]
Wurde das hier jemals gelöst? Denn das log ist voll von 

"This object will not be created in future versions. Please report this to the developer."
