### ISSUE TITLE
HELP: Usage outside iobroker

### ISSUE THREAD

**Issue by MaxBec** [SebastianSchultz/ioBroker.enet#28]
Hey guys,

i am from the home-assistant community and would love to integrate the gira enet server there.
I saw in another thread that you already got that working. Is there any chance to run and test your software outside iobroker?

And if how can i try it? A short tutorial would be great.

Kind Regards,
Max

**Comment by SebastianSchultz** [comment]
Sorry, but at the moment the scripts are still in very alpha state.
