### ISSUE TITLE
Add support for Jung/Gira eNet Server in the future?

### ISSUE THREAD

**Issue by SebastianSchultz** [SebastianSchultz/ioBroker.enet#3]
Add support for using the Jung/Gira eNet server AND/OR Jung/Gira Mobile Gateway with this adapter.

**Comment by SebastianSchultz** [comment]
https://forum.iobroker.net/viewtopic.php?f=36&t=10571&p=124818&hilit=enet#p124788

**Comment by SebastianSchultz** [comment]
Here are some scripts from user "stoffel67" at ioBroker forum.

Notice from him:

> So, hier mal meine Scripte, alles ziemlich "hemdsärmelig", bin nicht der geborene Programmierer....
> aber läuft bei mir momentan stabil.
> 
> Ablauf:
> ----------
> Login.json
> start_config.json
> get_locations.json
> 
> get_current_values.json ( -->Schleife)
> 
> es scheint auch ein get_event zu gehen, sodaß bei Änderungen eine Art PUSH kommt, funktioniert bei mir aber noch nicht richtig
> ebenso das logout geht noch nicht richtig ( wird aber im Betrieb nicht gebraucht, soll ja endlos laufen....)
> 
> kannst mal schauen, ob man damit was anfangen kann...
> 


[enet.zip](https://github.com/SebastianSchultz/ioBroker.enet/files/1899376/enet.zip)

**Comment by leonidas82** [comment]
Hallo Sebastian, konntest du an den eNet Server Script schon etwas weiter arbeiten. Bin sehr sehr neu hier: Wie bekomme ich die oben genannten skripte in ioBroker installiert? Würde gerne mein eNet System mit SONOS verknüpfen. Viele Grüße

**Comment by SebastianSchultz** [comment]
Hallo zusammen,

ich habe dieses Thema nicht vergessen, kann aber leider mangels eNet Server noch nicht mit der Entwicklung anfangen. Ich bin da aber dran evtl. ein Testgerät zu bekommen.

**Comment by leonidas82** [comment]
> Add support for using the Jung/Gira eNet server AND/OR Jung/Gira Mobile Gateway with this adapter.

Hallo Sebastian, wie ich freudig gesehen habe konntest du etwa weiterarbeiten am Adapter? Leider kann ich mich nicht an meinem Server via Adapter einloggen. gibts hier irgendwas zu beachten? VG, Leo

**Comment by SebastianSchultz** [comment]
Hallo Leo,

sorry, soweit ist der Adapter leider noch nicht :(
Mir fehlt immer noch der Server zum Testen. Sobald dieser da ist, gehts in der Entwicklung weiter!

**Comment by Bebelkahler** [comment]
Hallo Sebastian,
bist Du mit dem enet Server schon weitergekommen? Gibt es inzwischen eine Möglichkeit den Server anzubinden?
Danke und LG Andre

**Comment by SebastianSchultz** [comment]
Leider habe ich noch keinen Server.
Ein Bekannter von mir nutzt eNet und wil/wird sich einen Server zulegen.
Sobald er diesen hat, gehts mit der Entwicklung in Richtung Server weiter.

**Comment by kaikus** [comment]
darf ich mal fragen, bist Du schon weitergekommen mit der Server Anbindung ?

**Comment by SebastianSchultz** [comment]
Ich arbeite gerade dran.
Verbindungsaufbau und Login in den Server geht schon :)

**Comment by kaikus** [comment]
Falls ich etwas helfen kann, bitte melden !

**Comment by SebastianSchultz** [comment]
Wenn Du programmieren könntest wäre super :)
Momentan hakt es "nur" noch beim Setzen der Werte und Auslesen von Werten.

**Comment by Kater--S** [comment]
Irgendwie habe ich noch nicht den rechten Überblick, mit welcher Konfiguration hier gearbeitet wird…
Ich habe hier im Haus „produktiv“ einen Jung-eNet-Server mit Version 1.x und einem IP-Gateway. Das nutze ich seit ein paar Jahren mit einem Python-Skript, das über MQTT seine Anweisungen bekommt (das war noch ohne ioBroker, nur mit Node-RED). Funktioniert einigermaßen bei Licht (Dimmer), Schaltern und Rollläden.
Zum Testen habe ich jetzt zusätzlich mal einen eNet-Server mit V2-Software (dann ohne IP-Gateway) aufgesetzt.
Der ioBroker-eNet-Adapter mag aber mit allen drei Geräten nicht zusammenarbeiten. Können wir einander da vielleicht irgendwie helfen? ;-)

**Comment by SebastianSchultz** [comment]
Das Gateway sollte mit dem Adapter schon funktionieren, an der Implementierung des Servers bin ich gerade dran.
Ich habe für die Implementierung auch nur einen V2 Server hier.

**Comment by Kater--S** [comment]
Hm. Da komme ich jetzt nicht ganz mit ;-)
Das Gateway ist doch aus der V1-Welt und inzwischen abgekündigt. Mit der V2-Software wird der Server autonom betrieben. Oder?
Ich rede jetzt von der Jung-Variante – nehme aber an, bei Gira ist es genauso.

**Comment by SebastianSchultz** [comment]
Genau, der Server arbeitet autark. Der Server ist bei Jung und Gira gleich.

**Comment by Kater--S** [comment]
Dann unterstützt dein Adapter sowohl eNet V1 als auch (zukünftig?) V2?

**Comment by SebastianSchultz** [comment]
Also ich hab das alte Gateway schon mit dem Adapter genutzt. Und beim Server bin ich grad dran

**Comment by SebastianSchultz** [comment]
Entwicklung für die Unterstützung des eNet Servers läuft...

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Moin,
würdest du den aktuellen Stand schon teilen? Ich bin aus aktuellem Anlass gerade auf das Problem gestoßen (für homebridge). Ich selber kannte nicht den Unterschied zwischen Gateway und Server (da ich selber eine native KNX installation habe) ... Ich wollte schauen ob ich das für nen Freund ans laufen bekommen kann.

Evtl. kann ich auch helfen / unterstützen (kann programmieren ;-) )

**Comment by SebastianSchultz** [comment]
[iobroker.enet.zip](https://github.com/SebastianSchultz/ioBroker.enet/files/5371652/iobroker.enet.zip)

Das ist die derzeitige Fassung.
Evtl. kannst Du ja mithelfen?

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Cool, vielen Dank ... ja ich werd mir das nachher mal angucken.
Wie gesagt, ich selber hab nen richtiges KNX im Einsatz, bei nem bekannten aber remote zugriff auf ein eNet Server (V2).

Das was ich auf die schnelle überflogen habe hab ich soweit verstanden. Beim Gateway gabs das Socket. Das verhält sich jetzt wohl anders.

Ich werde meine Erkenntnisse auf jeden Fall auch mit dir teilen :-)

Gruß

**Comment by MaxBec** [comment]
Servus,

ich würde euch super gerne bei der Programmierung für den enet Server unterstützen. Wo kann ich mithelfen?

LG, Max

**Comment by SebastianSchultz** [comment]
Zwei Beiträge über Deinem findest Du die aktuelle Fassung.
Gern kannst Du da mithelfen :)

**Comment by MaxBec** [comment]
Servus Sebastian,
das habe ich schon entdeckt. Aber wie führe ich das Ganze ohne iobroker aus? Mir fehlt der richtige adapter. Gibt es da eine andere chance?

**Comment by SebastianSchultz** [comment]
Ohne ioBroker funktioniert das leider nicht.
Das Ganze ist ja quasi ein Adapter für ioBroker.
