### ISSUE TITLE
Dokumentation eNet Server API

### ISSUE THREAD

**Issue by joergpichler** [SebastianSchultz/ioBroker.enet#31]
Ich habe gesehen, dass hier mit vor wenigen Tagen die Kompatibilität mit eNet Server 2.3.0 implementiert wurde. Seit Jahren schreibe ich regelmäßig Mails an Jung dass sie doch bitte die API offenlegen sollen. Leider weigern sie sich und die paar Updates der App über die letzten Jahre lassen immernoch nicht die Automatisierung zu die ich gerne hätte.

Mein JS Kenntnisse reichen leider nicht den Code in cb3a617cad4c0f78bdb926ca3ade6f5a0636ffb1 zu verstehen. Ist die API irgendwo dokumentiert? Ich würde eine Library für die eNet Server API gerne in C# implementieren.

Danke!

**Comment by sweh** [comment]
Das sind genau meine Gedanken. Ich stände parat, um eine Library in Python zu implementieren.

**Comment by SebastianSchultz** [comment]
Aufgrund einer bestehenden rechtlich bindenden Geheimhaltungvereinbarung ist uns eine Veröffentlichung der API leider nicht möglich. Der Code musste demzufolge auch etwas verschlüsselt werden.
