### ISSUE TITLE
Implement auto-discovery function 

### ISSUE THREAD

**Issue by GermanBluefox** [SebastianSchultz/ioBroker.enet#7]
Examples: https://github.com/ioBroker/ioBroker.discovery/tree/master/lib/adapters

**Comment by SebastianSchultz** [comment]
Will do it if the implementation of eNet Server(!) is completed :)

**Comment by SebastianSchultz** [comment]
Added: [https://github.com/SebastianSchultz/ioBroker.discovery/pull/2](url)
